name: demo_yummy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  http: ^1.2.0
  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  curved_navigation_bar: ^1.0.6
  circular_profile_avatar: ^2.0.5
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.1


  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/


